// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scope/scope.proto

package scopepb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MyScopes struct {
	Path                 []string `protobuf:"bytes,1,rep,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MyScopes) Reset()         { *m = MyScopes{} }
func (m *MyScopes) String() string { return proto.CompactTextString(m) }
func (*MyScopes) ProtoMessage()    {}
func (*MyScopes) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0b6205683bb2257, []int{0}
}

func (m *MyScopes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyScopes.Unmarshal(m, b)
}
func (m *MyScopes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyScopes.Marshal(b, m, deterministic)
}
func (m *MyScopes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyScopes.Merge(m, src)
}
func (m *MyScopes) XXX_Size() int {
	return xxx_messageInfo_MyScopes.Size(m)
}
func (m *MyScopes) XXX_DiscardUnknown() {
	xxx_messageInfo_MyScopes.DiscardUnknown(m)
}

var xxx_messageInfo_MyScopes proto.InternalMessageInfo

func (m *MyScopes) GetPath() []string {
	if m != nil {
		return m.Path
	}
	return nil
}

var E_Scope = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*MyScopes)(nil),
	Field:         9966,
	Name:          "scopes.scope",
	Tag:           "bytes,9966,opt,name=scope",
	Filename:      "scope/scope.proto",
}

func init() {
	proto.RegisterType((*MyScopes)(nil), "scopes.MyScopes")
	proto.RegisterExtension(E_Scope)
}

func init() { proto.RegisterFile("scope/scope.proto", fileDescriptor_d0b6205683bb2257) }

var fileDescriptor_d0b6205683bb2257 = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x4e, 0xce, 0x2f,
	0x48, 0xd5, 0x07, 0x93, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x6c, 0x60, 0x4e, 0xb1, 0x94,
	0x42, 0x7a, 0x7e, 0x7e, 0x7a, 0x4e, 0xaa, 0x3e, 0x58, 0x34, 0xa9, 0x34, 0x4d, 0x3f, 0x25, 0xb5,
	0x38, 0xb9, 0x28, 0xb3, 0xa0, 0x24, 0xbf, 0x08, 0xa2, 0x52, 0x49, 0x8e, 0x8b, 0xc3, 0xb7, 0x32,
	0x18, 0xac, 0x5a, 0x48, 0x88, 0x8b, 0xa5, 0x20, 0xb1, 0x24, 0x43, 0x82, 0x51, 0x81, 0x59, 0x83,
	0x33, 0x08, 0xcc, 0xb6, 0x72, 0xe7, 0x62, 0x05, 0x9b, 0x25, 0x24, 0xa7, 0x07, 0x31, 0x4b, 0x0f,
	0x66, 0x96, 0x9e, 0x6f, 0x6a, 0x49, 0x46, 0x7e, 0x8a, 0x7f, 0x41, 0x49, 0x66, 0x7e, 0x5e, 0xb1,
	0xc4, 0x3b, 0x5f, 0x05, 0x46, 0x0d, 0x6e, 0x23, 0x01, 0x3d, 0x88, 0xd5, 0x7a, 0x30, 0x53, 0x83,
	0x20, 0xfa, 0x9d, 0x38, 0xa3, 0xd8, 0xc1, 0x8c, 0x82, 0xa4, 0x24, 0x36, 0xb0, 0x11, 0xc6, 0x80,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x40, 0x1c, 0x68, 0x4d, 0xb9, 0x00, 0x00, 0x00,
}
